version: '3'
services:
  flask:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5002:80
    depends_on:
      - flask